Feature/pom and gal 686 716
biorelate/ChemSpot pull request #1
Opened 2020-10-06 09:58 UTC by AlexandraDumitriu

2020-10-06 10:20 UTC, ADBalici requested changes
A couple of things to add to the README:

- can we add the external .jars to GCP and have this pull the jars from there? it would be much easier then
- write down the bash commands or any other steps necessary to build the final .jar (I'll try them out on my machine to see if it works). this will be the foundation of a TeamCity pipeline

2020-10-06 10:20 UTC, ADBalici commented on chemspot.iml
> +  <component name="NewModuleRootManager" LANGUAGE_LEVEL="JDK_1_5">
1.5? i thought we could do this with 1.8

2020-10-06 10:20 UTC, ADBalici commented on chemspot.iml
> +  <component name="NewModuleRootManager" LANGUAGE_LEVEL="JDK_1_5">
ah shit this is the .iml. please add the .iml and the .idea directory to gitignore

2020-10-06 12:17 UTC, AlexandraDumitriu commented on chemspot.iml
> +  <component name="NewModuleRootManager" LANGUAGE_LEVEL="JDK_1_5">
We could add these jars as packages in Artifact Registry (see Adding Packages from https://cloud.google.com/artifact-registry/docs/java/manage-packages#console). Then we could import them the way we do galactic4j. If this doesn't work, we can upload them to gcs and download them when needed.
As for bash commands, simply running "mvn prepare-package" should create the jar with dependencies.
To run "mvn package" (which also creates a release zip file with all the resources) make sure you have ids.zip and dict.zip locally and set project.package.data in the pom.xml to their location. I will add this to the README.

2020-10-07 12:36 UTC, ADBalici approved these changes

2020-10-07 12:36 UTC, merged